language: node_js

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH=$HOME/.meteor:$PATH

install:
  - meteor npm install

script:
  - meteor npm run test

cache:
  directories:
    - node_modules